//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncabezadoRecibo
    {
        public EncabezadoRecibo()
        {
            this.DetalleRecibo = new HashSet<DetalleRecibo>();
        }
    
        public int NumeroRecibo { get; set; }
        public Nullable<int> CodigoCliente { get; set; }
        public string FechaRecibo { get; set; }
        public Nullable<int> MontoRecibo { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual ICollection<DetalleRecibo> DetalleRecibo { get; set; }
    }
}
